name: pda_scanner_ns
description: This is a scanning plug-in for PDA to listen the scanned events and get scanning results (+ null safety).
version: 0.3.0

authors:
  - leyan95 <leyansorosame@gmail.com> - original version
  - kazbekbet <kazbekbet@gmail.com> - null safety migration

homepage:
  - https://github.com/leyan95/pda_scanner
  - https://github.com/kazbekbet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shinow.pda_scanner
        pluginClass: PdaScannerPlugin
